version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - ${DATASOURCE_PORT:-3306}:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      DATASOURCE_ROOT_PASSWORD: "$DATASOURCE_PASSWORD"
      DATASOURCE_DATABASE: "$DATASOURCE_DATABASE"
      DATASOURCE_USER: "$DATASOURCE_USER"
      DATASOURCE_PASSWORD: "$DATASOURCE_PASSWORD"
