version: 3
services:
  mysql:
    image: mysql:8.0
    ports:
      -3306:3306
    command: mysqld --character-set-server=utf8mb4 --collection-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: todo
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: todos